### ISSUE TITLE
PermissionError:

### ISSUE THREAD

**Issue by aladinor** [nasa/gesdisc-cloud-tutorials#2]
Hi everyone, 

I am trying to access IMERG data on aws bucket. I followed  [gesdics-tutorial](https://github.com/nasa/gesdisc-cloud-tutorials/blob/main/GES_DISC_Cloud_Notebooks/Cloud_Workshop/Staff/1_S3_Bucket_Access.ipynb) example as follows, 
``` python
from netrc import netrc
from subprocess import Popen
from getpass import getpass
import os
import requests
import s3fs

gesdisc_s3 = "https://data.gesdisc.earthdata.nasa.gov/s3credentials"

# Define a function for S3 access credentials


def begin_s3_direct_access(url: str=gesdisc_s3):
    response = requests.get(url).json()
    return s3fs.S3FileSystem(key=response['accessKeyId'],
                             secret=response['secretAccessKey'],
                             token=response['sessionToken'],
                             client_kwargs={'region_name': 'us-west-2'})


def main():
    urs = 'urs.earthdata.nasa.gov'  # Earthdata URL endpoint for authentication
    prompts = ['Enter NASA Earthdata Login Username: ',
               'Enter NASA Earthdata Login Password: ']

    netrc_name = ".netrc"

    # Determine if netrc file exists, and if so, if it includes NASA Earthdata Login Credentials
    try:
        netrcDir = os.path.expanduser(f"~/{netrc_name}")
        netrc(netrcDir).authenticators(urs)[0]

    # Below, create a netrc file and prompt user for NASA Earthdata Login Username and Password
    except FileNotFoundError:
        homeDir = os.path.expanduser("~")
        Popen('touch {0}{2} | echo machine {1} >> {0}{2}'.format(homeDir + os.sep, urs, netrc_name), shell=True)
        Popen('echo login {} >> {}{}'.format(getpass(prompt=prompts[0]), homeDir + os.sep, netrc_name), shell=True)
        Popen('echo \'password {} \'>> {}{}'.format(getpass(prompt=prompts[1]), homeDir + os.sep, netrc_name),
              shell=True)
        # Set restrictive permissions
        Popen('chmod 0600 {0}{1}'.format(homeDir + os.sep, netrc_name), shell=True)

    fs = begin_s3_direct_access()
    # Check that the file system is intact as an S3FileSystem object, which means that token is valid
    # Common causes of rejected S3 access tokens include incorrect passwords stored in the netrc file, or a non-existent netrc file
    # Files are organized by s3://gesdisc-cumulus-prod-protected/MERRA2/M2T1NXSLV.5.12.4/year/mo/*.nc4
    fn = 's3://gesdisc-cumulus-prod-protected/MERRA2/M2T1NXSLV.5.12.4/2019/03/MERRA2_400.tavg1_2d_slv_Nx.20190313.nc4'
    fs.info(fn) ## Error occurs when executing this line


if __name__ == "__main__":
    main()


```

However, I got the following error 

```python 
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```
Any ideas of what could be wrong?

Cheers, 

Alfonso

**Comment by alexishunzinger** [comment]
Hi Alfonso,

First question for you - do you know which AWS region you are running your compute resource in? NASA Earthdata is only accessible from the AWS region "us-west-2" currently. 

Fellow UIUC ATMS alum,
Alexis

**Comment by aladinor** [comment]
Hi @alexishunzinger , 

Thanks for your prompt reply. I am not completely sure what region I am in. I am currently in Urbana, IL. is there any way to check my AWS region?

**Comment by alexishunzinger** [comment]
How are you accessing AWS? Do you have your own account and access to an AWS Management Console where you launch resources from? Are you using a managed platform?

**Comment by aladinor** [comment]
@alexishunzinger I think I was completely wrong. I was trying to access the data using my computer. However, I think  I need to use amazon resources to access the data. I really appreciate your time I will continue looking for ways to access the data. 

Cheers, 

Alfonso

**Comment by alexishunzinger** [comment]
You're welcome, Alfonso. Have a look at some of the Data Access options on the [IMERG dataset landing page](https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGHH_06/summary?keywords=IMERG).

If you have any other data access questions, please reach out to our [Help Desk](https://disc.gsfc.nasa.gov/information/documents?title=Contact%20Us).
